version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      DB_HOST: mongodb://mongodb:27017/todoapp
      DB_PASSWORD: example
      DB_USER: root
      DB_NAME: todoapp
  mongodb:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: todoapp